#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Message
The message of the error
.PARAMETER Severity
The severity of the error
.OUTPUTS

ClusterMappingPciInnerChecksInner<PSCustomObject>
#>

function Initialize-PVEClusterMappingPciInnerChecksInner {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("warning", "error")]
        [String]
        ${Severity}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEClusterMappingPciInnerChecksInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


		 $DisplayNameMapping =@{
			"Message"="message"; "Severity"="severity"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClusterMappingPciInnerChecksInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClusterMappingPciInnerChecksInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClusterMappingPciInnerChecksInner<PSCustomObject>
#>
function ConvertFrom-PVEJsonToClusterMappingPciInnerChecksInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEClusterMappingPciInnerChecksInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEClusterMappingPciInnerChecksInner
        $AllProperties = ("message", "severity")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "severity"))) { #optional property not found
            $Severity = $null
        } else {
            $Severity = $JsonParameters.PSobject.Properties["severity"].value
        }

        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "severity" = ${Severity}
        }

        return $PSO
    }

}

