#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Checks
No description available.
.PARAMETER Map
No description available.
.PARAMETER Description
No description available.
.PARAMETER Id
No description available.
.OUTPUTS

ClusterMappingDirInner<PSCustomObject>
#>

function Initialize-PVEClusterMappingDirInner {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Checks},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Map},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEClusterMappingDirInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


		 $DisplayNameMapping =@{
			"Checks"="checks"; "Map"="map"; "Description"="description"; "Id"="id"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClusterMappingDirInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClusterMappingDirInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClusterMappingDirInner<PSCustomObject>
#>
function ConvertFrom-PVEJsonToClusterMappingDirInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEClusterMappingDirInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEClusterMappingDirInner
        $AllProperties = ("checks", "map", "description", "id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "checks"))) { #optional property not found
            $Checks = $null
        } else {
            $Checks = $JsonParameters.PSobject.Properties["checks"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "map"))) { #optional property not found
            $Map = $null
        } else {
            $Map = $JsonParameters.PSobject.Properties["map"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        $PSO = [PSCustomObject]@{
            "checks" = ${Checks}
            "map" = ${Map}
            "description" = ${Description}
            "id" = ${Id}
        }

        return $PSO
    }

}

