#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Mode
No description available.
.PARAMETER Target
No description available.
.PARAMETER Origin
No description available.
.PARAMETER Name
No description available.
.PARAMETER Disable
No description available.
.PARAMETER MatchSeverity
No description available.
.PARAMETER MatchField
No description available.
.PARAMETER MatchCalendar
No description available.
.PARAMETER Comment
No description available.
.PARAMETER InvertMatch
No description available.
.OUTPUTS

ClusterNotificationsMatchersGETInner<PSCustomObject>
#>

function Initialize-PVEClusterNotificationsMatchersGETInner {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("all", "any")]
        [String]
        ${Mode},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Target},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("user-created", "builtin", "modified-builtin")]
        [String]
        ${Origin},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Disable},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${MatchSeverity},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${MatchField},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${MatchCalendar},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Comment},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${InvertMatch}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEClusterNotificationsMatchersGETInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


		 $DisplayNameMapping =@{
			"Mode"="mode"; "Target"="target"; "Origin"="origin"; "Name"="name"; "Disable"="disable"; "MatchSeverity"="match-severity"; "MatchField"="match-field"; "MatchCalendar"="match-calendar"; "Comment"="comment"; "InvertMatch"="invert-match"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ClusterNotificationsMatchersGETInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to ClusterNotificationsMatchersGETInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ClusterNotificationsMatchersGETInner<PSCustomObject>
#>
function ConvertFrom-PVEJsonToClusterNotificationsMatchersGETInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEClusterNotificationsMatchersGETInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEClusterNotificationsMatchersGETInner
        $AllProperties = ("mode", "target", "origin", "name", "disable", "match-severity", "match-field", "match-calendar", "comment", "invert-match")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mode"))) { #optional property not found
            $Mode = $null
        } else {
            $Mode = $JsonParameters.PSobject.Properties["mode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target"))) { #optional property not found
            $Target = $null
        } else {
            $Target = $JsonParameters.PSobject.Properties["target"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "origin"))) { #optional property not found
            $Origin = $null
        } else {
            $Origin = $JsonParameters.PSobject.Properties["origin"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "disable"))) { #optional property not found
            $Disable = $null
        } else {
            $Disable = $JsonParameters.PSobject.Properties["disable"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "match-severity"))) { #optional property not found
            $MatchSeverity = $null
        } else {
            $MatchSeverity = $JsonParameters.PSobject.Properties["match-severity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "match-field"))) { #optional property not found
            $MatchField = $null
        } else {
            $MatchField = $JsonParameters.PSobject.Properties["match-field"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "match-calendar"))) { #optional property not found
            $MatchCalendar = $null
        } else {
            $MatchCalendar = $JsonParameters.PSobject.Properties["match-calendar"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "comment"))) { #optional property not found
            $Comment = $null
        } else {
            $Comment = $JsonParameters.PSobject.Properties["comment"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "invert-match"))) { #optional property not found
            $InvertMatch = $null
        } else {
            $InvertMatch = $JsonParameters.PSobject.Properties["invert-match"].value
        }

        $PSO = [PSCustomObject]@{
            "mode" = ${Mode}
            "target" = ${Target}
            "origin" = ${Origin}
            "name" = ${Name}
            "disable" = ${Disable}
            "match-severity" = ${MatchSeverity}
            "match-field" = ${MatchField}
            "match-calendar" = ${MatchCalendar}
            "comment" = ${Comment}
            "invert-match" = ${InvertMatch}
        }

        return $PSO
    }

}

