#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Ticket
No description available.
.PARAMETER Node
No description available.
.PARAMETER Vmid
No description available.
.PARAMETER Socket
No description available.
.OUTPUTS

GETNodesLxcMtunnelwebsocketRB<PSCustomObject>
#>

function Initialize-PVEGETNodesLxcMtunnelwebsocketRB {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Ticket},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Node},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Vmid},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Socket}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEGETNodesLxcMtunnelwebsocketRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Vmid -and $Vmid -gt 999999999) {
          throw "invalid value for 'Vmid', must be smaller than or equal to 999999999."
        }

        if ($Vmid -and $Vmid -lt 100) {
          throw "invalid value for 'Vmid', must be greater than or equal to 100."
        }


		 $DisplayNameMapping =@{
			"Ticket"="ticket"; "Node"="node"; "Vmid"="vmid"; "Socket"="socket"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = "$PSBoundParameters.$parameter"
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GETNodesLxcMtunnelwebsocketRB<PSCustomObject>

.DESCRIPTION

Convert from JSON to GETNodesLxcMtunnelwebsocketRB<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GETNodesLxcMtunnelwebsocketRB<PSCustomObject>
#>
function ConvertFrom-PVEJsonToGETNodesLxcMtunnelwebsocketRB {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEGETNodesLxcMtunnelwebsocketRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEGETNodesLxcMtunnelwebsocketRB
        $AllProperties = ("ticket", "node", "vmid", "socket")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ticket"))) { #optional property not found
            $Ticket = $null
        } else {
            $Ticket = $JsonParameters.PSobject.Properties["ticket"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "node"))) { #optional property not found
            $Node = $null
        } else {
            $Node = $JsonParameters.PSobject.Properties["node"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vmid"))) { #optional property not found
            $Vmid = $null
        } else {
            $Vmid = $JsonParameters.PSobject.Properties["vmid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "socket"))) { #optional property not found
            $Socket = $null
        } else {
            $Socket = $JsonParameters.PSobject.Properties["socket"].value
        }

        $PSO = [PSCustomObject]@{
            "ticket" = ${Ticket}
            "node" = ${Node}
            "vmid" = ${Vmid}
            "socket" = ${Socket}
        }

        return $PSO
    }

}

