#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Vendor
No description available.
.PARAMETER Name
No description available.
.PARAMETER Custom
No description available.
.OUTPUTS

NodesCapabilitiesQemuCpuInner<PSCustomObject>
#>

function Initialize-PVENodesCapabilitiesQemuCpuInner {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Vendor},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Custom}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVENodesCapabilitiesQemuCpuInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


		 $DisplayNameMapping =@{
			"Vendor"="vendor"; "Name"="name"; "Custom"="custom"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NodesCapabilitiesQemuCpuInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to NodesCapabilitiesQemuCpuInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NodesCapabilitiesQemuCpuInner<PSCustomObject>
#>
function ConvertFrom-PVEJsonToNodesCapabilitiesQemuCpuInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVENodesCapabilitiesQemuCpuInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVENodesCapabilitiesQemuCpuInner
        $AllProperties = ("vendor", "name", "custom")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vendor"))) { #optional property not found
            $Vendor = $null
        } else {
            $Vendor = $JsonParameters.PSobject.Properties["vendor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom"))) { #optional property not found
            $Custom = $null
        } else {
            $Custom = $JsonParameters.PSobject.Properties["custom"].value
        }

        $PSO = [PSCustomObject]@{
            "vendor" = ${Vendor}
            "name" = ${Name}
            "custom" = ${Custom}
        }

        return $PSO
    }

}

