#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VxlanLocalTunnelip
No description available.
.PARAMETER UplinkId
No description available.
.PARAMETER Address6
No description available.
.PARAMETER BondPrimary
No description available.
.PARAMETER Exists
No description available.
.PARAMETER Method
No description available.
.PARAMETER Netmask
No description available.
.PARAMETER BondXmitHashPolicy
No description available.
.PARAMETER Type
No description available.
.PARAMETER Netmask6
No description available.
.PARAMETER OvsTag
No description available.
.PARAMETER Mtu
No description available.
.PARAMETER BridgeArpNdSuppress
No description available.
.PARAMETER OvsOptions
No description available.
.PARAMETER Active
No description available.
.PARAMETER BridgeMulticastFlood
No description available.
.PARAMETER VlanProtocol
No description available.
.PARAMETER BridgePorts
No description available.
.PARAMETER Priority
No description available.
.PARAMETER VxlanPhysdev
No description available.
.PARAMETER BridgeLearning
No description available.
.PARAMETER Gateway6
No description available.
.PARAMETER VxlanId
No description available.
.PARAMETER OvsBonds
No description available.
.PARAMETER Comments
No description available.
.PARAMETER Method6
No description available.
.PARAMETER Autostart
No description available.
.PARAMETER Options6
No description available.
.PARAMETER OvsBridge
No description available.
.PARAMETER BridgeVlanAware
No description available.
.PARAMETER Comments6
No description available.
.PARAMETER Families
No description available.
.PARAMETER VlanId
No description available.
.PARAMETER Options
No description available.
.PARAMETER Gateway
No description available.
.PARAMETER Cidr
No description available.
.PARAMETER BridgeUnicastFlood
No description available.
.PARAMETER BridgeAccess
No description available.
.PARAMETER Cidr6
No description available.
.PARAMETER VxlanSvcnodeip
No description available.
.PARAMETER OvsPorts
No description available.
.PARAMETER LinkType
No description available.
.PARAMETER Iface
No description available.
.PARAMETER Slaves
No description available.
.PARAMETER VlanRawDevice
No description available.
.PARAMETER BridgeVids
No description available.
.PARAMETER Address
No description available.
.PARAMETER BondMode
No description available.
.OUTPUTS

NodesNetworkGETInner<PSCustomObject>
#>

function Initialize-PVENodesNetworkGETInner {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VxlanLocalTunnelip},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UplinkId},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Address6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BondPrimary},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Exists},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("loopback", "dhcp", "manual", "static", "auto")]
        [String]
        ${Method},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Netmask},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("layer2", "layer2+3", "layer3+4")]
        [String]
        ${BondXmitHashPolicy},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("bridge", "bond", "eth", "alias", "vlan", "OVSBridge", "OVSBond", "OVSPort", "OVSIntPort", "vnet", "unknown")]
        [String]
        ${Type},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Netmask6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${OvsTag},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Mtu},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BridgeArpNdSuppress},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OvsOptions},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Active},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BridgeMulticastFlood},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("802.1ad", "802.1q")]
        [String]
        ${VlanProtocol},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BridgePorts},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Priority},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VxlanPhysdev},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BridgeLearning},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Gateway6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${VxlanId},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OvsBonds},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Comments},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("loopback", "dhcp", "manual", "static", "auto")]
        [String]
        ${Method6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Autostart},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Options6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OvsBridge},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BridgeVlanAware},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Comments6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("inet", "inet6")]
        [String[]]
        ${Families},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${VlanId},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Options},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Gateway},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Cidr},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BridgeUnicastFlood},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${BridgeAccess},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Cidr6},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VxlanSvcnodeip},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OvsPorts},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LinkType},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Iface},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Slaves},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VlanRawDevice},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BridgeVids},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Address},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("balance-rr", "active-backup", "balance-xor", "broadcast", "802.3ad", "balance-tlb", "balance-alb", "balance-slb", "lacp-balance-slb", "lacp-balance-tcp")]
        [String]
        ${BondMode}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVENodesNetworkGETInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Netmask6 -and $Netmask6 -gt 128) {
          throw "invalid value for 'Netmask6', must be smaller than or equal to 128."
        }

        if ($OvsTag -and $OvsTag -gt 4094) {
          throw "invalid value for 'OvsTag', must be smaller than or equal to 4094."
        }

        if ($OvsTag -and $OvsTag -lt 1) {
          throw "invalid value for 'OvsTag', must be greater than or equal to 1."
        }

        if ($Mtu -and $Mtu -gt 65520) {
          throw "invalid value for 'Mtu', must be smaller than or equal to 65520."
        }

        if ($Mtu -and $Mtu -lt 1280) {
          throw "invalid value for 'Mtu', must be greater than or equal to 1280."
        }

        if (!$OvsOptions -and $OvsOptions.length -gt 1024) {
            throw "invalid value for 'OvsOptions', the character length must be smaller than or equal to 1024."
        }

        if ($VlanId -and $VlanId -gt 4094) {
          throw "invalid value for 'VlanId', must be smaller than or equal to 4094."
        }

        if ($VlanId -and $VlanId -lt 1) {
          throw "invalid value for 'VlanId', must be greater than or equal to 1."
        }

        if (!$Iface -and $Iface.length -gt 20) {
            throw "invalid value for 'Iface', the character length must be smaller than or equal to 20."
        }

        if (!$Iface -and $Iface.length -lt 2) {
            throw "invalid value for 'Iface', the character length must be great than or equal to 2."
        }


		 $DisplayNameMapping =@{
			"VxlanLocalTunnelip"="vxlan-local-tunnelip"; "UplinkId"="uplink-id"; "Address6"="address6"; "BondPrimary"="bond-primary"; "Exists"="exists"; "Method"="method"; "Netmask"="netmask"; "BondXmitHashPolicy"="bond_xmit_hash_policy"; "Type"="type"; "Netmask6"="netmask6"; "OvsTag"="ovs_tag"; "Mtu"="mtu"; "BridgeArpNdSuppress"="bridge-arp-nd-suppress"; "OvsOptions"="ovs_options"; "Active"="active"; "BridgeMulticastFlood"="bridge-multicast-flood"; "VlanProtocol"="vlan-protocol"; "BridgePorts"="bridge_ports"; "Priority"="priority"; "VxlanPhysdev"="vxlan-physdev"; "BridgeLearning"="bridge-learning"; "Gateway6"="gateway6"; "VxlanId"="vxlan-id"; "OvsBonds"="ovs_bonds"; "Comments"="comments"; "Method6"="method6"; "Autostart"="autostart"; "Options6"="options6"; "OvsBridge"="ovs_bridge"; "BridgeVlanAware"="bridge_vlan_aware"; "Comments6"="comments6"; "Families"="families"; "VlanId"="vlan-id"; "Options"="options"; "Gateway"="gateway"; "Cidr"="cidr"; "BridgeUnicastFlood"="bridge-unicast-flood"; "BridgeAccess"="bridge-access"; "Cidr6"="cidr6"; "VxlanSvcnodeip"="vxlan-svcnodeip"; "OvsPorts"="ovs_ports"; "LinkType"="link-type"; "Iface"="iface"; "Slaves"="slaves"; "VlanRawDevice"="vlan-raw-device"; "BridgeVids"="bridge_vids"; "Address"="address"; "BondMode"="bond_mode"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NodesNetworkGETInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to NodesNetworkGETInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NodesNetworkGETInner<PSCustomObject>
#>
function ConvertFrom-PVEJsonToNodesNetworkGETInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVENodesNetworkGETInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVENodesNetworkGETInner
        $AllProperties = ("vxlan-local-tunnelip", "uplink-id", "address6", "bond-primary", "exists", "method", "netmask", "bond_xmit_hash_policy", "type", "netmask6", "ovs_tag", "mtu", "bridge-arp-nd-suppress", "ovs_options", "active", "bridge-multicast-flood", "vlan-protocol", "bridge_ports", "priority", "vxlan-physdev", "bridge-learning", "gateway6", "vxlan-id", "ovs_bonds", "comments", "method6", "autostart", "options6", "ovs_bridge", "bridge_vlan_aware", "comments6", "families", "vlan-id", "options", "gateway", "cidr", "bridge-unicast-flood", "bridge-access", "cidr6", "vxlan-svcnodeip", "ovs_ports", "link-type", "iface", "slaves", "vlan-raw-device", "bridge_vids", "address", "bond_mode")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vxlan-local-tunnelip"))) { #optional property not found
            $VxlanLocalTunnelip = $null
        } else {
            $VxlanLocalTunnelip = $JsonParameters.PSobject.Properties["vxlan-local-tunnelip"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "uplink-id"))) { #optional property not found
            $UplinkId = $null
        } else {
            $UplinkId = $JsonParameters.PSobject.Properties["uplink-id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "address6"))) { #optional property not found
            $Address6 = $null
        } else {
            $Address6 = $JsonParameters.PSobject.Properties["address6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bond-primary"))) { #optional property not found
            $BondPrimary = $null
        } else {
            $BondPrimary = $JsonParameters.PSobject.Properties["bond-primary"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "exists"))) { #optional property not found
            $Exists = $null
        } else {
            $Exists = $JsonParameters.PSobject.Properties["exists"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "method"))) { #optional property not found
            $Method = $null
        } else {
            $Method = $JsonParameters.PSobject.Properties["method"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "netmask"))) { #optional property not found
            $Netmask = $null
        } else {
            $Netmask = $JsonParameters.PSobject.Properties["netmask"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bond_xmit_hash_policy"))) { #optional property not found
            $BondXmitHashPolicy = $null
        } else {
            $BondXmitHashPolicy = $JsonParameters.PSobject.Properties["bond_xmit_hash_policy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "netmask6"))) { #optional property not found
            $Netmask6 = $null
        } else {
            $Netmask6 = $JsonParameters.PSobject.Properties["netmask6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ovs_tag"))) { #optional property not found
            $OvsTag = $null
        } else {
            $OvsTag = $JsonParameters.PSobject.Properties["ovs_tag"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mtu"))) { #optional property not found
            $Mtu = $null
        } else {
            $Mtu = $JsonParameters.PSobject.Properties["mtu"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge-arp-nd-suppress"))) { #optional property not found
            $BridgeArpNdSuppress = $null
        } else {
            $BridgeArpNdSuppress = $JsonParameters.PSobject.Properties["bridge-arp-nd-suppress"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ovs_options"))) { #optional property not found
            $OvsOptions = $null
        } else {
            $OvsOptions = $JsonParameters.PSobject.Properties["ovs_options"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "active"))) { #optional property not found
            $Active = $null
        } else {
            $Active = $JsonParameters.PSobject.Properties["active"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge-multicast-flood"))) { #optional property not found
            $BridgeMulticastFlood = $null
        } else {
            $BridgeMulticastFlood = $JsonParameters.PSobject.Properties["bridge-multicast-flood"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vlan-protocol"))) { #optional property not found
            $VlanProtocol = $null
        } else {
            $VlanProtocol = $JsonParameters.PSobject.Properties["vlan-protocol"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge_ports"))) { #optional property not found
            $BridgePorts = $null
        } else {
            $BridgePorts = $JsonParameters.PSobject.Properties["bridge_ports"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "priority"))) { #optional property not found
            $Priority = $null
        } else {
            $Priority = $JsonParameters.PSobject.Properties["priority"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vxlan-physdev"))) { #optional property not found
            $VxlanPhysdev = $null
        } else {
            $VxlanPhysdev = $JsonParameters.PSobject.Properties["vxlan-physdev"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge-learning"))) { #optional property not found
            $BridgeLearning = $null
        } else {
            $BridgeLearning = $JsonParameters.PSobject.Properties["bridge-learning"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "gateway6"))) { #optional property not found
            $Gateway6 = $null
        } else {
            $Gateway6 = $JsonParameters.PSobject.Properties["gateway6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vxlan-id"))) { #optional property not found
            $VxlanId = $null
        } else {
            $VxlanId = $JsonParameters.PSobject.Properties["vxlan-id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ovs_bonds"))) { #optional property not found
            $OvsBonds = $null
        } else {
            $OvsBonds = $JsonParameters.PSobject.Properties["ovs_bonds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "comments"))) { #optional property not found
            $Comments = $null
        } else {
            $Comments = $JsonParameters.PSobject.Properties["comments"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "method6"))) { #optional property not found
            $Method6 = $null
        } else {
            $Method6 = $JsonParameters.PSobject.Properties["method6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "autostart"))) { #optional property not found
            $Autostart = $null
        } else {
            $Autostart = $JsonParameters.PSobject.Properties["autostart"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "options6"))) { #optional property not found
            $Options6 = $null
        } else {
            $Options6 = $JsonParameters.PSobject.Properties["options6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ovs_bridge"))) { #optional property not found
            $OvsBridge = $null
        } else {
            $OvsBridge = $JsonParameters.PSobject.Properties["ovs_bridge"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge_vlan_aware"))) { #optional property not found
            $BridgeVlanAware = $null
        } else {
            $BridgeVlanAware = $JsonParameters.PSobject.Properties["bridge_vlan_aware"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "comments6"))) { #optional property not found
            $Comments6 = $null
        } else {
            $Comments6 = $JsonParameters.PSobject.Properties["comments6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "families"))) { #optional property not found
            $Families = $null
        } else {
            $Families = $JsonParameters.PSobject.Properties["families"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vlan-id"))) { #optional property not found
            $VlanId = $null
        } else {
            $VlanId = $JsonParameters.PSobject.Properties["vlan-id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "options"))) { #optional property not found
            $Options = $null
        } else {
            $Options = $JsonParameters.PSobject.Properties["options"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "gateway"))) { #optional property not found
            $Gateway = $null
        } else {
            $Gateway = $JsonParameters.PSobject.Properties["gateway"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cidr"))) { #optional property not found
            $Cidr = $null
        } else {
            $Cidr = $JsonParameters.PSobject.Properties["cidr"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge-unicast-flood"))) { #optional property not found
            $BridgeUnicastFlood = $null
        } else {
            $BridgeUnicastFlood = $JsonParameters.PSobject.Properties["bridge-unicast-flood"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge-access"))) { #optional property not found
            $BridgeAccess = $null
        } else {
            $BridgeAccess = $JsonParameters.PSobject.Properties["bridge-access"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cidr6"))) { #optional property not found
            $Cidr6 = $null
        } else {
            $Cidr6 = $JsonParameters.PSobject.Properties["cidr6"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vxlan-svcnodeip"))) { #optional property not found
            $VxlanSvcnodeip = $null
        } else {
            $VxlanSvcnodeip = $JsonParameters.PSobject.Properties["vxlan-svcnodeip"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ovs_ports"))) { #optional property not found
            $OvsPorts = $null
        } else {
            $OvsPorts = $JsonParameters.PSobject.Properties["ovs_ports"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "link-type"))) { #optional property not found
            $LinkType = $null
        } else {
            $LinkType = $JsonParameters.PSobject.Properties["link-type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iface"))) { #optional property not found
            $Iface = $null
        } else {
            $Iface = $JsonParameters.PSobject.Properties["iface"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "slaves"))) { #optional property not found
            $Slaves = $null
        } else {
            $Slaves = $JsonParameters.PSobject.Properties["slaves"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vlan-raw-device"))) { #optional property not found
            $VlanRawDevice = $null
        } else {
            $VlanRawDevice = $JsonParameters.PSobject.Properties["vlan-raw-device"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bridge_vids"))) { #optional property not found
            $BridgeVids = $null
        } else {
            $BridgeVids = $JsonParameters.PSobject.Properties["bridge_vids"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "address"))) { #optional property not found
            $Address = $null
        } else {
            $Address = $JsonParameters.PSobject.Properties["address"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bond_mode"))) { #optional property not found
            $BondMode = $null
        } else {
            $BondMode = $JsonParameters.PSobject.Properties["bond_mode"].value
        }

        $PSO = [PSCustomObject]@{
            "vxlan-local-tunnelip" = ${VxlanLocalTunnelip}
            "uplink-id" = ${UplinkId}
            "address6" = ${Address6}
            "bond-primary" = ${BondPrimary}
            "exists" = ${Exists}
            "method" = ${Method}
            "netmask" = ${Netmask}
            "bond_xmit_hash_policy" = ${BondXmitHashPolicy}
            "type" = ${Type}
            "netmask6" = ${Netmask6}
            "ovs_tag" = ${OvsTag}
            "mtu" = ${Mtu}
            "bridge-arp-nd-suppress" = ${BridgeArpNdSuppress}
            "ovs_options" = ${OvsOptions}
            "active" = ${Active}
            "bridge-multicast-flood" = ${BridgeMulticastFlood}
            "vlan-protocol" = ${VlanProtocol}
            "bridge_ports" = ${BridgePorts}
            "priority" = ${Priority}
            "vxlan-physdev" = ${VxlanPhysdev}
            "bridge-learning" = ${BridgeLearning}
            "gateway6" = ${Gateway6}
            "vxlan-id" = ${VxlanId}
            "ovs_bonds" = ${OvsBonds}
            "comments" = ${Comments}
            "method6" = ${Method6}
            "autostart" = ${Autostart}
            "options6" = ${Options6}
            "ovs_bridge" = ${OvsBridge}
            "bridge_vlan_aware" = ${BridgeVlanAware}
            "comments6" = ${Comments6}
            "families" = ${Families}
            "vlan-id" = ${VlanId}
            "options" = ${Options}
            "gateway" = ${Gateway}
            "cidr" = ${Cidr}
            "bridge-unicast-flood" = ${BridgeUnicastFlood}
            "bridge-access" = ${BridgeAccess}
            "cidr6" = ${Cidr6}
            "vxlan-svcnodeip" = ${VxlanSvcnodeip}
            "ovs_ports" = ${OvsPorts}
            "link-type" = ${LinkType}
            "iface" = ${Iface}
            "slaves" = ${Slaves}
            "vlan-raw-device" = ${VlanRawDevice}
            "bridge_vids" = ${BridgeVids}
            "address" = ${Address}
            "bond_mode" = ${BondMode}
        }

        return $PSO
    }

}

