#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Content
No description available.
.PARAMETER Truncated
No description available.
.OUTPUTS

NodesQemuAgentFileread<PSCustomObject>
#>

function Initialize-PVENodesQemuAgentFileread {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Content},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Truncated}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVENodesQemuAgentFileread' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Truncated -and $Truncated -gt 1) {
          throw "invalid value for 'Truncated', must be smaller than or equal to 1."
        }

        if ($Truncated -and $Truncated -lt 0) {
          throw "invalid value for 'Truncated', must be greater than or equal to 0."
        }


		 $DisplayNameMapping =@{
			"Content"="content"; "Truncated"="truncated"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = "$PSBoundParameters.$parameter"
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NodesQemuAgentFileread<PSCustomObject>

.DESCRIPTION

Convert from JSON to NodesQemuAgentFileread<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NodesQemuAgentFileread<PSCustomObject>
#>
function ConvertFrom-PVEJsonToNodesQemuAgentFileread {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVENodesQemuAgentFileread' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVENodesQemuAgentFileread
        $AllProperties = ("content", "truncated")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "content"))) { #optional property not found
            $Content = $null
        } else {
            $Content = $JsonParameters.PSobject.Properties["content"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "truncated"))) { #optional property not found
            $Truncated = $null
        } else {
            $Truncated = $JsonParameters.PSobject.Properties["truncated"].value
        }

        $PSO = [PSCustomObject]@{
            "content" = ${Content}
            "truncated" = ${Truncated}
        }

        return $PSO
    }

}

