#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TargetBridge
No description available.
.PARAMETER Online
No description available.
.PARAMETER TargetStorage
No description available.
.PARAMETER Delete
No description available.
.PARAMETER Timeout
No description available.
.PARAMETER Restart
No description available.
.PARAMETER TargetVmid
No description available.
.PARAMETER Bwlimit
No description available.
.PARAMETER TargetEndpoint
No description available.
.OUTPUTS

POSTNodesLxcRemotemigrateRB<PSCustomObject>
#>

function Initialize-PVEPOSTNodesLxcRemotemigrateRB {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TargetBridge},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Online},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TargetStorage},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Delete},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Timeout},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Restart},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${TargetVmid},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Bwlimit},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TargetEndpoint}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEPOSTNodesLxcRemotemigrateRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($TargetVmid -and $TargetVmid -gt 999999999) {
          throw "invalid value for 'TargetVmid', must be smaller than or equal to 999999999."
        }

        if ($TargetVmid -and $TargetVmid -lt 100) {
          throw "invalid value for 'TargetVmid', must be greater than or equal to 100."
        }


		 $DisplayNameMapping =@{
			"TargetBridge"="target-bridge"; "Online"="online"; "TargetStorage"="target-storage"; "Delete"="delete"; "Timeout"="timeout"; "Restart"="restart"; "TargetVmid"="target-vmid"; "Bwlimit"="bwlimit"; "TargetEndpoint"="target-endpoint"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to POSTNodesLxcRemotemigrateRB<PSCustomObject>

.DESCRIPTION

Convert from JSON to POSTNodesLxcRemotemigrateRB<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

POSTNodesLxcRemotemigrateRB<PSCustomObject>
#>
function ConvertFrom-PVEJsonToPOSTNodesLxcRemotemigrateRB {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEPOSTNodesLxcRemotemigrateRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEPOSTNodesLxcRemotemigrateRB
        $AllProperties = ("target-bridge", "online", "target-storage", "delete", "timeout", "restart", "target-vmid", "bwlimit", "target-endpoint")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target-bridge"))) { #optional property not found
            $TargetBridge = $null
        } else {
            $TargetBridge = $JsonParameters.PSobject.Properties["target-bridge"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "online"))) { #optional property not found
            $Online = $null
        } else {
            $Online = $JsonParameters.PSobject.Properties["online"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target-storage"))) { #optional property not found
            $TargetStorage = $null
        } else {
            $TargetStorage = $JsonParameters.PSobject.Properties["target-storage"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "delete"))) { #optional property not found
            $Delete = $null
        } else {
            $Delete = $JsonParameters.PSobject.Properties["delete"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timeout"))) { #optional property not found
            $Timeout = $null
        } else {
            $Timeout = $JsonParameters.PSobject.Properties["timeout"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "restart"))) { #optional property not found
            $Restart = $null
        } else {
            $Restart = $JsonParameters.PSobject.Properties["restart"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target-vmid"))) { #optional property not found
            $TargetVmid = $null
        } else {
            $TargetVmid = $JsonParameters.PSobject.Properties["target-vmid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bwlimit"))) { #optional property not found
            $Bwlimit = $null
        } else {
            $Bwlimit = $JsonParameters.PSobject.Properties["bwlimit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target-endpoint"))) { #optional property not found
            $TargetEndpoint = $null
        } else {
            $TargetEndpoint = $JsonParameters.PSobject.Properties["target-endpoint"].value
        }

        $PSO = [PSCustomObject]@{
            "target-bridge" = ${TargetBridge}
            "online" = ${Online}
            "target-storage" = ${TargetStorage}
            "delete" = ${Delete}
            "timeout" = ${Timeout}
            "restart" = ${Restart}
            "target-vmid" = ${TargetVmid}
            "bwlimit" = ${Bwlimit}
            "target-endpoint" = ${TargetEndpoint}
        }

        return $PSO
    }

}

