#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER GeneratePassword
No description available.
.PARAMETER Websocket
No description available.
.OUTPUTS

POSTNodesQemuVncproxyRB<PSCustomObject>
#>

function Initialize-PVEPOSTNodesQemuVncproxyRB {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${GeneratePassword},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Websocket}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEPOSTNodesQemuVncproxyRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


		 $DisplayNameMapping =@{
			"GeneratePassword"="generate-password"; "Websocket"="websocket"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to POSTNodesQemuVncproxyRB<PSCustomObject>

.DESCRIPTION

Convert from JSON to POSTNodesQemuVncproxyRB<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

POSTNodesQemuVncproxyRB<PSCustomObject>
#>
function ConvertFrom-PVEJsonToPOSTNodesQemuVncproxyRB {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEPOSTNodesQemuVncproxyRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEPOSTNodesQemuVncproxyRB
        $AllProperties = ("generate-password", "websocket")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "generate-password"))) { #optional property not found
            $GeneratePassword = $null
        } else {
            $GeneratePassword = $JsonParameters.PSobject.Properties["generate-password"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "websocket"))) { #optional property not found
            $Websocket = $null
        } else {
            $Websocket = $JsonParameters.PSobject.Properties["websocket"].value
        }

        $PSO = [PSCustomObject]@{
            "generate-password" = ${GeneratePassword}
            "websocket" = ${Websocket}
        }

        return $PSO
    }

}

