#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CrushRule
No description available.
.PARAMETER PgNum
No description available.
.PARAMETER AddStorages
No description available.
.PARAMETER Size
No description available.
.PARAMETER PgNumMin
No description available.
.PARAMETER MinSize
No description available.
.PARAMETER ErasureCoding
No description available.
.PARAMETER TargetSizeRatio
No description available.
.PARAMETER PgAutoscaleMode
No description available.
.PARAMETER Name
No description available.
.PARAMETER TargetSize
No description available.
.PARAMETER Application
No description available.
.OUTPUTS

POSTNodesCephPoolRB<PSCustomObject>
#>

function Initialize-PVEPOSTNodesCephPoolRB {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CrushRule},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${PgNum},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${AddStorages},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Size},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${PgNumMin},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MinSize},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ErasureCoding},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${TargetSizeRatio},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("on", "off", "warn")]
        [String]
        ${PgAutoscaleMode},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("(?^:^[^:/\s]+$)")]
        [String]
        ${Name},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^(\d+(\.\d+)?)([KMGT])?$")]
        [String]
        ${TargetSize},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("rbd", "cephfs", "rgw")]
        [String]
        ${Application}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEPOSTNodesCephPoolRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($PgNum -and $PgNum -gt 32768) {
          throw "invalid value for 'PgNum', must be smaller than or equal to 32768."
        }

        if ($PgNum -and $PgNum -lt 1) {
          throw "invalid value for 'PgNum', must be greater than or equal to 1."
        }

        if ($Size -and $Size -gt 7) {
          throw "invalid value for 'Size', must be smaller than or equal to 7."
        }

        if ($Size -and $Size -lt 1) {
          throw "invalid value for 'Size', must be greater than or equal to 1."
        }

        if ($PgNumMin -and $PgNumMin -gt 32768) {
          throw "invalid value for 'PgNumMin', must be smaller than or equal to 32768."
        }

        if ($MinSize -and $MinSize -gt 7) {
          throw "invalid value for 'MinSize', must be smaller than or equal to 7."
        }

        if ($MinSize -and $MinSize -lt 1) {
          throw "invalid value for 'MinSize', must be greater than or equal to 1."
        }


		 $DisplayNameMapping =@{
			"CrushRule"="crush_rule"; "PgNum"="pg_num"; "AddStorages"="add_storages"; "Size"="size"; "PgNumMin"="pg_num_min"; "MinSize"="min_size"; "ErasureCoding"="erasure-coding"; "TargetSizeRatio"="target_size_ratio"; "PgAutoscaleMode"="pg_autoscale_mode"; "Name"="name"; "TargetSize"="target_size"; "Application"="application"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to POSTNodesCephPoolRB<PSCustomObject>

.DESCRIPTION

Convert from JSON to POSTNodesCephPoolRB<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

POSTNodesCephPoolRB<PSCustomObject>
#>
function ConvertFrom-PVEJsonToPOSTNodesCephPoolRB {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEPOSTNodesCephPoolRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEPOSTNodesCephPoolRB
        $AllProperties = ("crush_rule", "pg_num", "add_storages", "size", "pg_num_min", "min_size", "erasure-coding", "target_size_ratio", "pg_autoscale_mode", "name", "target_size", "application")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "crush_rule"))) { #optional property not found
            $CrushRule = $null
        } else {
            $CrushRule = $JsonParameters.PSobject.Properties["crush_rule"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pg_num"))) { #optional property not found
            $PgNum = $null
        } else {
            $PgNum = $JsonParameters.PSobject.Properties["pg_num"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "add_storages"))) { #optional property not found
            $AddStorages = $null
        } else {
            $AddStorages = $JsonParameters.PSobject.Properties["add_storages"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "size"))) { #optional property not found
            $Size = $null
        } else {
            $Size = $JsonParameters.PSobject.Properties["size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pg_num_min"))) { #optional property not found
            $PgNumMin = $null
        } else {
            $PgNumMin = $JsonParameters.PSobject.Properties["pg_num_min"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "min_size"))) { #optional property not found
            $MinSize = $null
        } else {
            $MinSize = $JsonParameters.PSobject.Properties["min_size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "erasure-coding"))) { #optional property not found
            $ErasureCoding = $null
        } else {
            $ErasureCoding = $JsonParameters.PSobject.Properties["erasure-coding"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target_size_ratio"))) { #optional property not found
            $TargetSizeRatio = $null
        } else {
            $TargetSizeRatio = $JsonParameters.PSobject.Properties["target_size_ratio"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pg_autoscale_mode"))) { #optional property not found
            $PgAutoscaleMode = $null
        } else {
            $PgAutoscaleMode = $JsonParameters.PSobject.Properties["pg_autoscale_mode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target_size"))) { #optional property not found
            $TargetSize = $null
        } else {
            $TargetSize = $JsonParameters.PSobject.Properties["target_size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "application"))) { #optional property not found
            $Application = $null
        } else {
            $Application = $JsonParameters.PSobject.Properties["application"].value
        }

        $PSO = [PSCustomObject]@{
            "crush_rule" = ${CrushRule}
            "pg_num" = ${PgNum}
            "add_storages" = ${AddStorages}
            "size" = ${Size}
            "pg_num_min" = ${PgNumMin}
            "min_size" = ${MinSize}
            "erasure-coding" = ${ErasureCoding}
            "target_size_ratio" = ${TargetSizeRatio}
            "pg_autoscale_mode" = ${PgAutoscaleMode}
            "name" = ${Name}
            "target_size" = ${TargetSize}
            "application" = ${Application}
        }

        return $PSO
    }

}

