#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ForceStop
No description available.
.PARAMETER Vms
No description available.
.PARAMETER Timeout
No description available.
.OUTPUTS

POSTNodesStopallRB<PSCustomObject>
#>

function Initialize-PVEPOSTNodesStopallRB {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ForceStop},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Vms},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Timeout}
    )

    Process {
        'Creating PSCustomObject: ProxmoxPVE => PVEPOSTNodesStopallRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Timeout -and $Timeout -gt 7200) {
          throw "invalid value for 'Timeout', must be smaller than or equal to 7200."
        }


		 $DisplayNameMapping =@{
			"ForceStop"="force-stop"; "Vms"="vms"; "Timeout"="timeout"
        }
		
		 $OBJ = @{}
		foreach($parameter in   $PSBoundParameters.Keys){
			#If Specifield map the Display name back
			$OBJ.($DisplayNameMapping.($parameter)) = $PSBoundParameters.$parameter
		}

		$PSO = [PSCustomObject]$OBJ


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to POSTNodesStopallRB<PSCustomObject>

.DESCRIPTION

Convert from JSON to POSTNodesStopallRB<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

POSTNodesStopallRB<PSCustomObject>
#>
function ConvertFrom-PVEJsonToPOSTNodesStopallRB {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: ProxmoxPVE => PVEPOSTNodesStopallRB' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PVEPOSTNodesStopallRB
        $AllProperties = ("force-stop", "vms", "timeout")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "force-stop"))) { #optional property not found
            $ForceStop = $null
        } else {
            $ForceStop = $JsonParameters.PSobject.Properties["force-stop"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vms"))) { #optional property not found
            $Vms = $null
        } else {
            $Vms = $JsonParameters.PSobject.Properties["vms"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timeout"))) { #optional property not found
            $Timeout = $null
        } else {
            $Timeout = $JsonParameters.PSobject.Properties["timeout"].value
        }

        $PSO = [PSCustomObject]@{
            "force-stop" = ${ForceStop}
            "vms" = ${Vms}
            "timeout" = ${Timeout}
        }

        return $PSO
    }

}

