#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPVEPoolsApi' {
    Context 'Get-PVEPools' {
        It 'Test Get-PVEPools' {
            #$TestResult = Get-PVEPools -GETPoolsRB "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-PVEPoolsByPoolid' {
        It 'Test Get-PVEPoolsByPoolid' {
            #$TestResult = Get-PVEPoolsByPoolid -Poolid "TEST_VALUE" -GETPoolsRB "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-PVEPools' {
        It 'Test New-PVEPools' {
            #$TestResult = New-PVEPools -POSTPoolsRB "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-PVEPools' {
        It 'Test Remove-PVEPools' {
            #$TestResult = Remove-PVEPools -DELETEPoolsRB "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-PVEPoolsByPoolid' {
        It 'Test Remove-PVEPoolsByPoolid' {
            #$TestResult = Remove-PVEPoolsByPoolid -Poolid "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-PVEPools' {
        It 'Test Set-PVEPools' {
            #$TestResult = Set-PVEPools -PUTPoolsRB "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-PVEPoolsByPoolid' {
        It 'Test Set-PVEPoolsByPoolid' {
            #$TestResult = Set-PVEPoolsByPoolid -Poolid "TEST_VALUE" -PUTPoolsRB "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
