#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEAccessUsersTokenPOSTInfo' {
    Context 'PVEAccessUsersTokenPOSTInfo' {
        It 'Initialize-PVEAccessUsersTokenPOSTInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEAccessUsersTokenPOSTInfo -Comment "TEST_VALUE" -Expire "TEST_VALUE" -Privsep "TEST_VALUE"
            #$NewObject | Should -BeOfType AccessUsersTokenPOSTInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
