#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEAccessAclInner' {
    Context 'PVEAccessAclInner' {
        It 'Initialize-PVEAccessAclInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEAccessAclInner -Propagate "TEST_VALUE" -Roleid "TEST_VALUE" -Path "TEST_VALUE" -Ugid "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType AccessAclInner
            #$NewObject.property | Should -Be 0
        }
    }
}
