#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEAccessTfaGETAVInner' {
    Context 'PVEAccessTfaGETAVInner' {
        It 'Initialize-PVEAccessTfaGETAVInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEAccessTfaGETAVInner -Description "TEST_VALUE" -Id "TEST_VALUE" -Created "TEST_VALUE" -Enable "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType AccessTfaGETAVInner
            #$NewObject.property | Should -Be 0
        }
    }
}
