#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEAccessUsersTfa' {
    Context 'PVEAccessUsersTfa' {
        It 'Initialize-PVEAccessUsersTfa' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEAccessUsersTfa -Realm "TEST_VALUE" -User "TEST_VALUE" -Types "TEST_VALUE"
            #$NewObject | Should -BeOfType AccessUsersTfa
            #$NewObject.property | Should -Be 0
        }
    }
}
