#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterConfigJoin' {
    Context 'PVEClusterConfigJoin' {
        It 'Initialize-PVEClusterConfigJoin' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterConfigJoin -Nodelist "TEST_VALUE" -PreferredNode "TEST_VALUE" -ConfigDigest "TEST_VALUE" -Totem "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterConfigJoin
            #$NewObject.property | Should -Be 0
        }
    }
}
