#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterNotificationsEndpointsSendmailGETInner' {
    Context 'PVEClusterNotificationsEndpointsSendmailGETInner' {
        It 'Initialize-PVEClusterNotificationsEndpointsSendmailGETInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterNotificationsEndpointsSendmailGETInner -Name "TEST_VALUE" -Mailto "TEST_VALUE" -Comment "TEST_VALUE" -Origin "TEST_VALUE" -MailtoUser "TEST_VALUE" -FromAddress "TEST_VALUE" -Author "TEST_VALUE" -Disable "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterNotificationsEndpointsSendmailGETInner
            #$NewObject.property | Should -Be 0
        }
    }
}
