#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterJobsRealmsyncInner' {
    Context 'PVEClusterJobsRealmsyncInner' {
        It 'Initialize-PVEClusterJobsRealmsyncInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterJobsRealmsyncInner -RemoveVanished "TEST_VALUE" -Id "TEST_VALUE" -NextRun "TEST_VALUE" -Comment "TEST_VALUE" -Enabled "TEST_VALUE" -Realm "TEST_VALUE" -Scope "TEST_VALUE" -Schedule "TEST_VALUE" -LastRun "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterJobsRealmsyncInner
            #$NewObject.property | Should -Be 0
        }
    }
}
