#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterSdnControllersInner' {
    Context 'PVEClusterSdnControllersInner' {
        It 'Initialize-PVEClusterSdnControllersInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterSdnControllersInner -Pending "TEST_VALUE" -State "TEST_VALUE" -Controller "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterSdnControllersInner
            #$NewObject.property | Should -Be 0
        }
    }
}
