#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterSdnVnetsFirewallOptions' {
    Context 'PVEClusterSdnVnetsFirewallOptions' {
        It 'Initialize-PVEClusterSdnVnetsFirewallOptions' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterSdnVnetsFirewallOptions -Enable "TEST_VALUE" -PolicyForward "TEST_VALUE" -LogLevelForward "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterSdnVnetsFirewallOptions
            #$NewObject.property | Should -Be 0
        }
    }
}
