#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterAcmeAccount' {
    Context 'PVEClusterAcmeAccount' {
        It 'Initialize-PVEClusterAcmeAccount' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterAcmeAccount -Directory "TEST_VALUE" -Location "TEST_VALUE" -Account "TEST_VALUE" -Tos "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterAcmeAccount
            #$NewObject.property | Should -Be 0
        }
    }
}
