#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterSdnInner' {
    Context 'PVEClusterSdnInner' {
        It 'Initialize-PVEClusterSdnInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterSdnInner -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterSdnInner
            #$NewObject.property | Should -Be 0
        }
    }
}
