#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterHaResources' {
    Context 'PVEClusterHaResources' {
        It 'Initialize-PVEClusterHaResources' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterHaResources -MaxRestart "TEST_VALUE" -MaxRelocate "TEST_VALUE" -Comment "TEST_VALUE" -Type "TEST_VALUE" -Group "TEST_VALUE" -State "TEST_VALUE" -Digest "TEST_VALUE" -Sid "TEST_VALUE" -Failback "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterHaResources
            #$NewObject.property | Should -Be 0
        }
    }
}
