#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterMappingUsbInner' {
    Context 'PVEClusterMappingUsbInner' {
        It 'Initialize-PVEClusterMappingUsbInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterMappingUsbInner -Id "TEST_VALUE" -VarError "TEST_VALUE" -Description "TEST_VALUE" -Map "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterMappingUsbInner
            #$NewObject.property | Should -Be 0
        }
    }
}
