#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterMappingDirInnerChecksInner' {
    Context 'PVEClusterMappingDirInnerChecksInner' {
        It 'Initialize-PVEClusterMappingDirInnerChecksInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterMappingDirInnerChecksInner -Message "TEST_VALUE" -Severity "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterMappingDirInnerChecksInner
            #$NewObject.property | Should -Be 0
        }
    }
}
