#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterFirewallMacrosInner' {
    Context 'PVEClusterFirewallMacrosInner' {
        It 'Initialize-PVEClusterFirewallMacrosInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterFirewallMacrosInner -Macro "TEST_VALUE" -Descr "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterFirewallMacrosInner
            #$NewObject.property | Should -Be 0
        }
    }
}
