#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterFirewallMacrosInner' {
    Context 'PVEClusterFirewallMacrosInner' {
        It 'Initialize-PVEClusterFirewallMacrosInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterFirewallMacrosInner -Descr "TEST_VALUE" -Macro "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterFirewallMacrosInner
            #$NewObject.property | Should -Be 0
        }
    }
}
