#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterNotificationsEndpointsWebhook' {
    Context 'PVEClusterNotificationsEndpointsWebhook' {
        It 'Initialize-PVEClusterNotificationsEndpointsWebhook' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterNotificationsEndpointsWebhook -Header "TEST_VALUE" -Body "TEST_VALUE" -Comment "TEST_VALUE" -Method "TEST_VALUE" -Disable "TEST_VALUE" -Secret "TEST_VALUE" -Url "TEST_VALUE" -Digest "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterNotificationsEndpointsWebhook
            #$NewObject.property | Should -Be 0
        }
    }
}
