#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterConfigNodes' {
    Context 'PVEClusterConfigNodes' {
        It 'Initialize-PVEClusterConfigNodes' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterConfigNodes -Warnings "TEST_VALUE" -CorosyncAuthkey "TEST_VALUE" -CorosyncConf "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterConfigNodes
            #$NewObject.property | Should -Be 0
        }
    }
}
