#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterBackupIncludedvolumes' {
    Context 'PVEClusterBackupIncludedvolumes' {
        It 'Initialize-PVEClusterBackupIncludedvolumes' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterBackupIncludedvolumes -Children "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterBackupIncludedvolumes
            #$NewObject.property | Should -Be 0
        }
    }
}
