#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEClusterNotificationsEndpointsSendmailGETInner' {
    Context 'PVEClusterNotificationsEndpointsSendmailGETInner' {
        It 'Initialize-PVEClusterNotificationsEndpointsSendmailGETInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEClusterNotificationsEndpointsSendmailGETInner -Origin "TEST_VALUE" -Name "TEST_VALUE" -Mailto "TEST_VALUE" -Disable "TEST_VALUE" -MailtoUser "TEST_VALUE" -FromAddress "TEST_VALUE" -Author "TEST_VALUE" -Comment "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterNotificationsEndpointsSendmailGETInner
            #$NewObject.property | Should -Be 0
        }
    }
}
