#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEDELETENodesQemuFirewallAliasesRB' {
    Context 'PVEDELETENodesQemuFirewallAliasesRB' {
        It 'Initialize-PVEDELETENodesQemuFirewallAliasesRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEDELETENodesQemuFirewallAliasesRB -Digest "TEST_VALUE" -Name "TEST_VALUE" -Vmid "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType DELETENodesQemuFirewallAliasesRB
            #$NewObject.property | Should -Be 0
        }
    }
}
