#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETAccessUsersTfaRB' {
    Context 'PVEGETAccessUsersTfaRB' {
        It 'Initialize-PVEGETAccessUsersTfaRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETAccessUsersTfaRB -Userid "TEST_VALUE" -Multiple "TEST_VALUE"
            #$NewObject | Should -BeOfType GETAccessUsersTfaRB
            #$NewObject.property | Should -Be 0
        }
    }
}
