#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETAccessUsersRB' {
    Context 'PVEGETAccessUsersRB' {
        It 'Initialize-PVEGETAccessUsersRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETAccessUsersRB -Full "TEST_VALUE" -Enabled "TEST_VALUE"
            #$NewObject | Should -BeOfType GETAccessUsersRB
            #$NewObject.property | Should -Be 0
        }
    }
}
