#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETClusterSdnControllersRB' {
    Context 'PVEGETClusterSdnControllersRB' {
        It 'Initialize-PVEGETClusterSdnControllersRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETClusterSdnControllersRB -Pending "TEST_VALUE" -Running "TEST_VALUE"
            #$NewObject | Should -BeOfType GETClusterSdnControllersRB
            #$NewObject.property | Should -Be 0
        }
    }
}
