#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETClusterAcmeTosRB' {
    Context 'PVEGETClusterAcmeTosRB' {
        It 'Initialize-PVEGETClusterAcmeTosRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETClusterAcmeTosRB -Directory "TEST_VALUE"
            #$NewObject | Should -BeOfType GETClusterAcmeTosRB
            #$NewObject.property | Should -Be 0
        }
    }
}
