#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesLxcFirewallLogRB' {
    Context 'PVEGETNodesLxcFirewallLogRB' {
        It 'Initialize-PVEGETNodesLxcFirewallLogRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesLxcFirewallLogRB -Since "TEST_VALUE" -Limit "TEST_VALUE" -VarUntil "TEST_VALUE" -Start "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesLxcFirewallLogRB
            #$NewObject.property | Should -Be 0
        }
    }
}
