#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesQemuFeatureRB' {
    Context 'PVEGETNodesQemuFeatureRB' {
        It 'Initialize-PVEGETNodesQemuFeatureRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesQemuFeatureRB -Snapname "TEST_VALUE" -Feature "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesQemuFeatureRB
            #$NewObject.property | Should -Be 0
        }
    }
}
