#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesFirewallLogRB' {
    Context 'PVEGETNodesFirewallLogRB' {
        It 'Initialize-PVEGETNodesFirewallLogRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesFirewallLogRB -Since "TEST_VALUE" -VarUntil "TEST_VALUE" -Limit "TEST_VALUE" -Start "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesFirewallLogRB
            #$NewObject.property | Should -Be 0
        }
    }
}
