#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesVzdumpExtractconfigRB' {
    Context 'PVEGETNodesVzdumpExtractconfigRB' {
        It 'Initialize-PVEGETNodesVzdumpExtractconfigRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesVzdumpExtractconfigRB -Volume "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesVzdumpExtractconfigRB
            #$NewObject.property | Should -Be 0
        }
    }
}
