#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesTasksRB' {
    Context 'PVEGETNodesTasksRB' {
        It 'Initialize-PVEGETNodesTasksRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesTasksRB -Userfilter "TEST_VALUE" -VarUntil "TEST_VALUE" -Since "TEST_VALUE" -Node "TEST_VALUE" -Limit "TEST_VALUE" -Vmid "TEST_VALUE" -Statusfilter "TEST_VALUE" -Source "TEST_VALUE" -Errors "TEST_VALUE" -Start "TEST_VALUE" -Typefilter "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesTasksRB
            #$NewObject.property | Should -Be 0
        }
    }
}
