#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesCephLogRB' {
    Context 'PVEGETNodesCephLogRB' {
        It 'Initialize-PVEGETNodesCephLogRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesCephLogRB -Start "TEST_VALUE" -Limit "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesCephLogRB
            #$NewObject.property | Should -Be 0
        }
    }
}
