#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesStorageRrddataRB' {
    Context 'PVEGETNodesStorageRrddataRB' {
        It 'Initialize-PVEGETNodesStorageRrddataRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesStorageRrddataRB -Storage "TEST_VALUE" -Cf "TEST_VALUE" -Node "TEST_VALUE" -Timeframe "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesStorageRrddataRB
            #$NewObject.property | Should -Be 0
        }
    }
}
