#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesQemuRrdRB' {
    Context 'PVEGETNodesQemuRrdRB' {
        It 'Initialize-PVEGETNodesQemuRrdRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesQemuRrdRB -Cf "TEST_VALUE" -Ds "TEST_VALUE" -Timeframe "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesQemuRrdRB
            #$NewObject.property | Should -Be 0
        }
    }
}
