#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesStoragePrunebackupsRB' {
    Context 'PVEGETNodesStoragePrunebackupsRB' {
        It 'Initialize-PVEGETNodesStoragePrunebackupsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesStoragePrunebackupsRB -Type "TEST_VALUE" -Vmid "TEST_VALUE" -PruneBackups "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesStoragePrunebackupsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
