#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesVncwebsocketRB' {
    Context 'PVEGETNodesVncwebsocketRB' {
        It 'Initialize-PVEGETNodesVncwebsocketRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesVncwebsocketRB -Port "TEST_VALUE" -Vncticket "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesVncwebsocketRB
            #$NewObject.property | Should -Be 0
        }
    }
}
