#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesQemuFirewallLogRB' {
    Context 'PVEGETNodesQemuFirewallLogRB' {
        It 'Initialize-PVEGETNodesQemuFirewallLogRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesQemuFirewallLogRB -VarUntil "TEST_VALUE" -Limit "TEST_VALUE" -Node "TEST_VALUE" -Vmid "TEST_VALUE" -Since "TEST_VALUE" -Start "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesQemuFirewallLogRB
            #$NewObject.property | Should -Be 0
        }
    }
}
