#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesQueryurlmetadataRB' {
    Context 'PVEGETNodesQueryurlmetadataRB' {
        It 'Initialize-PVEGETNodesQueryurlmetadataRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesQueryurlmetadataRB -VerifyCertificates "TEST_VALUE" -Url "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesQueryurlmetadataRB
            #$NewObject.property | Should -Be 0
        }
    }
}
