#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesCephCfgValueRB' {
    Context 'PVEGETNodesCephCfgValueRB' {
        It 'Initialize-PVEGETNodesCephCfgValueRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesCephCfgValueRB -ConfigKeys "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesCephCfgValueRB
            #$NewObject.property | Should -Be 0
        }
    }
}
