#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesStoragePrunebackupsRB' {
    Context 'PVEGETNodesStoragePrunebackupsRB' {
        It 'Initialize-PVEGETNodesStoragePrunebackupsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesStoragePrunebackupsRB -Node "TEST_VALUE" -Type "TEST_VALUE" -Storage "TEST_VALUE" -PruneBackups "TEST_VALUE" -Vmid "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesStoragePrunebackupsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
