#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesVncwebsocketRB' {
    Context 'PVEGETNodesVncwebsocketRB' {
        It 'Initialize-PVEGETNodesVncwebsocketRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesVncwebsocketRB -Port "TEST_VALUE" -Vncticket "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesVncwebsocketRB
            #$NewObject.property | Should -Be 0
        }
    }
}
