#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEGETNodesQemuFirewallLogRB' {
    Context 'PVEGETNodesQemuFirewallLogRB' {
        It 'Initialize-PVEGETNodesQemuFirewallLogRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEGETNodesQemuFirewallLogRB -Limit "TEST_VALUE" -Start "TEST_VALUE" -Since "TEST_VALUE" -VarUntil "TEST_VALUE"
            #$NewObject | Should -BeOfType GETNodesQemuFirewallLogRB
            #$NewObject.property | Should -Be 0
        }
    }
}
