#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesDisksZfsGETInner' {
    Context 'PVENodesDisksZfsGETInner' {
        It 'Initialize-PVENodesDisksZfsGETInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesDisksZfsGETInner -Dedup "TEST_VALUE" -Size "TEST_VALUE" -Frag "TEST_VALUE" -Alloc "TEST_VALUE" -Health "TEST_VALUE" -Free "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesDisksZfsGETInner
            #$NewObject.property | Should -Be 0
        }
    }
}
