#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesStatusMemory' {
    Context 'PVENodesStatusMemory' {
        It 'Initialize-PVENodesStatusMemory' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesStatusMemory -Free "TEST_VALUE" -Total "TEST_VALUE" -Used "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesStatusMemory
            #$NewObject.property | Should -Be 0
        }
    }
}
