#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuPendingInner' {
    Context 'PVENodesQemuPendingInner' {
        It 'Initialize-PVENodesQemuPendingInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuPendingInner -Key "TEST_VALUE" -Pending "TEST_VALUE" -Delete "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuPendingInner
            #$NewObject.property | Should -Be 0
        }
    }
}
