#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesLxcFirewallRulesGETInner' {
    Context 'PVENodesLxcFirewallRulesGETInner' {
        It 'Initialize-PVENodesLxcFirewallRulesGETInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesLxcFirewallRulesGETInner -Pos "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesLxcFirewallRulesGETInner
            #$NewObject.property | Should -Be 0
        }
    }
}
