#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesLxcInner' {
    Context 'PVENodesLxcInner' {
        It 'Initialize-PVENodesLxcInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesLxcInner -Cpu "TEST_VALUE" -Maxmem "TEST_VALUE" -Maxdisk "TEST_VALUE" -Diskwrite "TEST_VALUE" -Uptime "TEST_VALUE" -Tags "TEST_VALUE" -Diskread "TEST_VALUE" -Vmid "TEST_VALUE" -Template "TEST_VALUE" -Lock "TEST_VALUE" -Maxswap "TEST_VALUE" -Status "TEST_VALUE" -Cpus "TEST_VALUE" -Netout "TEST_VALUE" -Name "TEST_VALUE" -Disk "TEST_VALUE" -Mem "TEST_VALUE" -Netin "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesLxcInner
            #$NewObject.property | Should -Be 0
        }
    }
}
