#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesDisksLvmthinInner' {
    Context 'PVENodesDisksLvmthinInner' {
        It 'Initialize-PVENodesDisksLvmthinInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesDisksLvmthinInner -MetadataSize "TEST_VALUE" -LvSize "TEST_VALUE" -Lv "TEST_VALUE" -MetadataUsed "TEST_VALUE" -Vg "TEST_VALUE" -Used "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesDisksLvmthinInner
            #$NewObject.property | Should -Be 0
        }
    }
}
