#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesStoragePrunebackupsInner' {
    Context 'PVENodesStoragePrunebackupsInner' {
        It 'Initialize-PVENodesStoragePrunebackupsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesStoragePrunebackupsInner -Mark "TEST_VALUE" -Vmid "TEST_VALUE" -Type "TEST_VALUE" -Ctime "TEST_VALUE" -Volid "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesStoragePrunebackupsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
