#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesLxcSnapshotInner' {
    Context 'PVENodesLxcSnapshotInner' {
        It 'Initialize-PVENodesLxcSnapshotInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesLxcSnapshotInner -Snaptime "TEST_VALUE" -Description "TEST_VALUE" -Parent "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesLxcSnapshotInner
            #$NewObject.property | Should -Be 0
        }
    }
}
