#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuFeature' {
    Context 'PVENodesQemuFeature' {
        It 'Initialize-PVENodesQemuFeature' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuFeature -Nodes "TEST_VALUE" -HasFeature "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuFeature
            #$NewObject.property | Should -Be 0
        }
    }
}
