#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuMtunnelwebsocket' {
    Context 'PVENodesQemuMtunnelwebsocket' {
        It 'Initialize-PVENodesQemuMtunnelwebsocket' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuMtunnelwebsocket -Socket "TEST_VALUE" -Port "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuMtunnelwebsocket
            #$NewObject.property | Should -Be 0
        }
    }
}
