#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesDisksZfsChildrenInner' {
    Context 'PVENodesDisksZfsChildrenInner' {
        It 'Initialize-PVENodesDisksZfsChildrenInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesDisksZfsChildrenInner -Cksum "TEST_VALUE" -Msg "TEST_VALUE" -Name "TEST_VALUE" -Read "TEST_VALUE" -State "TEST_VALUE" -Write "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesDisksZfsChildrenInner
            #$NewObject.property | Should -Be 0
        }
    }
}
