#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesSdnZonesBridgesInnerPortsInner' {
    Context 'PVENodesSdnZonesBridgesInnerPortsInner' {
        It 'Initialize-PVENodesSdnZonesBridgesInnerPortsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesSdnZonesBridgesInnerPortsInner -Index "TEST_VALUE" -Name "TEST_VALUE" -PrimaryVlan "TEST_VALUE" -Vlans "TEST_VALUE" -Vmid "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesSdnZonesBridgesInnerPortsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
