#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesAptRepositoriesFilesInnerRepositoriesInnerOptionsInner' {
    Context 'PVENodesAptRepositoriesFilesInnerRepositoriesInnerOptionsInner' {
        It 'Initialize-PVENodesAptRepositoriesFilesInnerRepositoriesInnerOptionsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesAptRepositoriesFilesInnerRepositoriesInnerOptionsInner -Key "TEST_VALUE" -Values "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesAptRepositoriesFilesInnerRepositoriesInnerOptionsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
