#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuMigrate' {
    Context 'PVENodesQemuMigrate' {
        It 'Initialize-PVENodesQemuMigrate' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuMigrate -AllowedNodes "TEST_VALUE" -Running "TEST_VALUE" -NotAllowedNodes "TEST_VALUE" -MappedResourceInfo "TEST_VALUE" -LocalResources "TEST_VALUE" -MappedResources "TEST_VALUE" -LocalDisks "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuMigrate
            #$NewObject.property | Should -Be 0
        }
    }
}
