#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesScanLvmInner' {
    Context 'PVENodesScanLvmInner' {
        It 'Initialize-PVENodesScanLvmInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesScanLvmInner -Vg "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesScanLvmInner
            #$NewObject.property | Should -Be 0
        }
    }
}
