#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesAptRepositories' {
    Context 'PVENodesAptRepositories' {
        It 'Initialize-PVENodesAptRepositories' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesAptRepositories -StandardRepos "TEST_VALUE" -Digest "TEST_VALUE" -Infos "TEST_VALUE" -Files "TEST_VALUE" -Errors "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesAptRepositories
            #$NewObject.property | Should -Be 0
        }
    }
}
