#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesCephMdsInner' {
    Context 'PVENodesCephMdsInner' {
        It 'Initialize-PVENodesCephMdsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesCephMdsInner -StandbyReplay "TEST_VALUE" -Rank "TEST_VALUE" -VarHost "TEST_VALUE" -State "TEST_VALUE" -Addr "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesCephMdsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
