#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuFirewallAliasesInner' {
    Context 'PVENodesQemuFirewallAliasesInner' {
        It 'Initialize-PVENodesQemuFirewallAliasesInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuFirewallAliasesInner -Digest "TEST_VALUE" -Cidr "TEST_VALUE" -Comment "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuFirewallAliasesInner
            #$NewObject.property | Should -Be 0
        }
    }
}
