#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesScanLvmthinInner' {
    Context 'PVENodesScanLvmthinInner' {
        It 'Initialize-PVENodesScanLvmthinInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesScanLvmthinInner -Lv "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesScanLvmthinInner
            #$NewObject.property | Should -Be 0
        }
    }
}
