#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuAgentFileread' {
    Context 'PVENodesQemuAgentFileread' {
        It 'Initialize-PVENodesQemuAgentFileread' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuAgentFileread -Truncated "TEST_VALUE" -Content "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuAgentFileread
            #$NewObject.property | Should -Be 0
        }
    }
}
