#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesCephMgrInner' {
    Context 'PVENodesCephMgrInner' {
        It 'Initialize-PVENodesCephMgrInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesCephMgrInner -VarHost "TEST_VALUE" -Addr "TEST_VALUE" -State "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesCephMgrInner
            #$NewObject.property | Should -Be 0
        }
    }
}
