#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesCephOsdMetadataOsd' {
    Context 'PVENodesCephOsdMetadataOsd' {
        It 'Initialize-PVENodesCephOsdMetadataOsd' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesCephOsdMetadataOsd -BackAddr "TEST_VALUE" -FrontAddr "TEST_VALUE" -HbBackAddr "TEST_VALUE" -HbFrontAddr "TEST_VALUE" -Hostname "TEST_VALUE" -Id "TEST_VALUE" -MemUsage "TEST_VALUE" -OsdData "TEST_VALUE" -OsdObjectstore "TEST_VALUE" -VarPid "TEST_VALUE" -Version "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesCephOsdMetadataOsd
            #$NewObject.property | Should -Be 0
        }
    }
}
