#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuSnapshotInner' {
    Context 'PVENodesQemuSnapshotInner' {
        It 'Initialize-PVENodesQemuSnapshotInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuSnapshotInner -Description "TEST_VALUE" -Parent "TEST_VALUE" -Vmstate "TEST_VALUE" -Name "TEST_VALUE" -Snaptime "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuSnapshotInner
            #$NewObject.property | Should -Be 0
        }
    }
}
