#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPoolsMembersInner' {
    Context 'PVEPoolsMembersInner' {
        It 'Initialize-PVEPoolsMembersInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPoolsMembersInner -Id "TEST_VALUE" -Node "TEST_VALUE" -Storage "TEST_VALUE" -Type "TEST_VALUE" -Vmid "TEST_VALUE"
            #$NewObject | Should -BeOfType PoolsMembersInner
            #$NewObject.property | Should -Be 0
        }
    }
}
