#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesLxcFirewallAliasesRB' {
    Context 'PVEPOSTNodesLxcFirewallAliasesRB' {
        It 'Initialize-PVEPOSTNodesLxcFirewallAliasesRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesLxcFirewallAliasesRB -Comment "TEST_VALUE" -Name "TEST_VALUE" -Cidr "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesLxcFirewallAliasesRB
            #$NewObject.property | Should -Be 0
        }
    }
}
