#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesLxcStatusRebootRB' {
    Context 'PVEPOSTNodesLxcStatusRebootRB' {
        It 'Initialize-PVEPOSTNodesLxcStatusRebootRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesLxcStatusRebootRB -Node "TEST_VALUE" -Vmid "TEST_VALUE" -Timeout "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesLxcStatusRebootRB
            #$NewObject.property | Should -Be 0
        }
    }
}
