#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesCertificatesCustomRB' {
    Context 'PVEPOSTNodesCertificatesCustomRB' {
        It 'Initialize-PVEPOSTNodesCertificatesCustomRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesCertificatesCustomRB -Certificates "TEST_VALUE" -Key "TEST_VALUE" -Restart "TEST_VALUE" -Force "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesCertificatesCustomRB
            #$NewObject.property | Should -Be 0
        }
    }
}
