#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesQemuMigrateRB' {
    Context 'PVEPOSTNodesQemuMigrateRB' {
        It 'Initialize-PVEPOSTNodesQemuMigrateRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesQemuMigrateRB -Force "TEST_VALUE" -Target "TEST_VALUE" -Bwlimit "TEST_VALUE" -MigrationType "TEST_VALUE" -Vmid "TEST_VALUE" -Online "TEST_VALUE" -MigrationNetwork "TEST_VALUE" -Node "TEST_VALUE" -Targetstorage "TEST_VALUE" -WithLocalDisks "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesQemuMigrateRB
            #$NewObject.property | Should -Be 0
        }
    }
}
