#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesQemuVncproxyRB' {
    Context 'PVEPOSTNodesQemuVncproxyRB' {
        It 'Initialize-PVEPOSTNodesQemuVncproxyRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesQemuVncproxyRB -Vmid "TEST_VALUE" -GeneratePassword "TEST_VALUE" -Websocket "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesQemuVncproxyRB
            #$NewObject.property | Should -Be 0
        }
    }
}
