#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterSdnVnetsRB' {
    Context 'PVEPOSTClusterSdnVnetsRB' {
        It 'Initialize-PVEPOSTClusterSdnVnetsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterSdnVnetsRB -IsolatePorts "TEST_VALUE" -Alias "TEST_VALUE" -Type "TEST_VALUE" -Vnet "TEST_VALUE" -Vlanaware "TEST_VALUE" -Zone "TEST_VALUE" -Tag "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterSdnVnetsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
