#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTPoolsRB' {
    Context 'PVEPOSTPoolsRB' {
        It 'Initialize-PVEPOSTPoolsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTPoolsRB -Comment "TEST_VALUE" -Poolid "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTPoolsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
