#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterAcmeAccountRB' {
    Context 'PVEPOSTClusterAcmeAccountRB' {
        It 'Initialize-PVEPOSTClusterAcmeAccountRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterAcmeAccountRB -EabKid "TEST_VALUE" -EabHmacKey "TEST_VALUE" -Directory "TEST_VALUE" -TosUrl "TEST_VALUE" -Contact "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterAcmeAccountRB
            #$NewObject.property | Should -Be 0
        }
    }
}
