#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesAptRepositoriesRB' {
    Context 'PVEPOSTNodesAptRepositoriesRB' {
        It 'Initialize-PVEPOSTNodesAptRepositoriesRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesAptRepositoriesRB -Enabled "TEST_VALUE" -Index "TEST_VALUE" -Path "TEST_VALUE" -Digest "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesAptRepositoriesRB
            #$NewObject.property | Should -Be 0
        }
    }
}
