#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTAccessTfaRB' {
    Context 'PVEPOSTAccessTfaRB' {
        It 'Initialize-PVEPOSTAccessTfaRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTAccessTfaRB -Password "TEST_VALUE" -Type "TEST_VALUE" -Challenge "TEST_VALUE" -Description "TEST_VALUE" -Value "TEST_VALUE" -Userid "TEST_VALUE" -Totp "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTAccessTfaRB
            #$NewObject.property | Should -Be 0
        }
    }
}
