#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterSdnIpamsRB' {
    Context 'PVEPOSTClusterSdnIpamsRB' {
        It 'Initialize-PVEPOSTClusterSdnIpamsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterSdnIpamsRB -Url "TEST_VALUE" -LockToken "TEST_VALUE" -Token "TEST_VALUE" -Section "TEST_VALUE" -Type "TEST_VALUE" -Fingerprint "TEST_VALUE" -Ipam "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterSdnIpamsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
