#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesQemuFirewallAliasesRB' {
    Context 'PVEPOSTNodesQemuFirewallAliasesRB' {
        It 'Initialize-PVEPOSTNodesQemuFirewallAliasesRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesQemuFirewallAliasesRB -Comment "TEST_VALUE" -Name "TEST_VALUE" -Cidr "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesQemuFirewallAliasesRB
            #$NewObject.property | Should -Be 0
        }
    }
}
