#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesQemuTermproxyRB' {
    Context 'PVEPOSTNodesQemuTermproxyRB' {
        It 'Initialize-PVEPOSTNodesQemuTermproxyRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesQemuTermproxyRB -Node "TEST_VALUE" -Vmid "TEST_VALUE" -Serial "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesQemuTermproxyRB
            #$NewObject.property | Should -Be 0
        }
    }
}
