#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterSdnIpamsRB' {
    Context 'PVEPOSTClusterSdnIpamsRB' {
        It 'Initialize-PVEPOSTClusterSdnIpamsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterSdnIpamsRB -Type "TEST_VALUE" -Ipam "TEST_VALUE" -Section "TEST_VALUE" -Fingerprint "TEST_VALUE" -Token "TEST_VALUE" -Url "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterSdnIpamsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
