#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterFirewallRulesRB' {
    Context 'PVEPOSTClusterFirewallRulesRB' {
        It 'Initialize-PVEPOSTClusterFirewallRulesRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterFirewallRulesRB -Digest "TEST_VALUE" -Source "TEST_VALUE" -Sport "TEST_VALUE" -Action "TEST_VALUE" -Comment "TEST_VALUE" -Proto "TEST_VALUE" -Enable "TEST_VALUE" -IcmpType "TEST_VALUE" -Macro "TEST_VALUE" -Pos "TEST_VALUE" -Type "TEST_VALUE" -Iface "TEST_VALUE" -Log "TEST_VALUE" -Dest "TEST_VALUE" -Dport "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterFirewallRulesRB
            #$NewObject.property | Should -Be 0
        }
    }
}
