#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterSdnDnsRB' {
    Context 'PVEPOSTClusterSdnDnsRB' {
        It 'Initialize-PVEPOSTClusterSdnDnsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterSdnDnsRB -Type "TEST_VALUE" -Reversev6mask "TEST_VALUE" -Ttl "TEST_VALUE" -Reversemaskv6 "TEST_VALUE" -Url "TEST_VALUE" -Fingerprint "TEST_VALUE" -Dns "TEST_VALUE" -Key "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterSdnDnsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
