#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesDisksZfsRB' {
    Context 'PVEPOSTNodesDisksZfsRB' {
        It 'Initialize-PVEPOSTNodesDisksZfsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesDisksZfsRB -Compression "TEST_VALUE" -Raidlevel "TEST_VALUE" -Devices "TEST_VALUE" -DraidConfig "TEST_VALUE" -AddStorage "TEST_VALUE" -Name "TEST_VALUE" -Ashift "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesDisksZfsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
