#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesQemuAgentRB' {
    Context 'PVEPOSTNodesQemuAgentRB' {
        It 'Initialize-PVEPOSTNodesQemuAgentRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesQemuAgentRB -Command "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesQemuAgentRB
            #$NewObject.property | Should -Be 0
        }
    }
}
