#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterAcmeAccountRB' {
    Context 'PVEPOSTClusterAcmeAccountRB' {
        It 'Initialize-PVEPOSTClusterAcmeAccountRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterAcmeAccountRB -TosUrl "TEST_VALUE" -Contact "TEST_VALUE" -EabKid "TEST_VALUE" -EabHmacKey "TEST_VALUE" -Name "TEST_VALUE" -Directory "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterAcmeAccountRB
            #$NewObject.property | Should -Be 0
        }
    }
}
