#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesAptUpdateRB' {
    Context 'PVEPOSTNodesAptUpdateRB' {
        It 'Initialize-PVEPOSTNodesAptUpdateRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesAptUpdateRB -Quiet "TEST_VALUE" -Notify "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesAptUpdateRB
            #$NewObject.property | Should -Be 0
        }
    }
}
