#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesCephPoolRB' {
    Context 'PVEPOSTNodesCephPoolRB' {
        It 'Initialize-PVEPOSTNodesCephPoolRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesCephPoolRB -AddStorages "TEST_VALUE" -PgNumMin "TEST_VALUE" -PgNum "TEST_VALUE" -TargetSize "TEST_VALUE" -MinSize "TEST_VALUE" -Node "TEST_VALUE" -CrushRule "TEST_VALUE" -Size "TEST_VALUE" -TargetSizeRatio "TEST_VALUE" -Name "TEST_VALUE" -Application "TEST_VALUE" -ErasureCoding "TEST_VALUE" -PgAutoscaleMode "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesCephPoolRB
            #$NewObject.property | Should -Be 0
        }
    }
}
