#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTNodesQemuStatusResetRB' {
    Context 'PVEPOSTNodesQemuStatusResetRB' {
        It 'Initialize-PVEPOSTNodesQemuStatusResetRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTNodesQemuStatusResetRB -Vmid "TEST_VALUE" -Skiplock "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTNodesQemuStatusResetRB
            #$NewObject.property | Should -Be 0
        }
    }
}
