#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPOSTClusterConfigRB' {
    Context 'PVEPOSTClusterConfigRB' {
        It 'Initialize-PVEPOSTClusterConfigRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPOSTClusterConfigRB -Votes "TEST_VALUE" -Nodeid "TEST_VALUE" -LinkN "TEST_VALUE" -Clustername "TEST_VALUE"
            #$NewObject | Should -BeOfType POSTClusterConfigRB
            #$NewObject.property | Should -Be 0
        }
    }
}
