#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTAccessTfaRB' {
    Context 'PVEPUTAccessTfaRB' {
        It 'Initialize-PVEPUTAccessTfaRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTAccessTfaRB -Enable "TEST_VALUE" -Password "TEST_VALUE" -Id "TEST_VALUE" -Userid "TEST_VALUE" -Description "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTAccessTfaRB
            #$NewObject.property | Should -Be 0
        }
    }
}
