#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.0.8
# Version: 9.0.8
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTAccessUsersRB' {
    Context 'PVEPUTAccessUsersRB' {
        It 'Initialize-PVEPUTAccessUsersRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTAccessUsersRB -Enable "TEST_VALUE" -Keys "TEST_VALUE" -Groups "TEST_VALUE" -Lastname "TEST_VALUE" -Email "TEST_VALUE" -Comment "TEST_VALUE" -Firstname "TEST_VALUE" -Expire "TEST_VALUE" -Append "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTAccessUsersRB
            #$NewObject.property | Should -Be 0
        }
    }
}
