#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterSdnVnetsFirewallOptionsRB' {
    Context 'PVEPUTClusterSdnVnetsFirewallOptionsRB' {
        It 'Initialize-PVEPUTClusterSdnVnetsFirewallOptionsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterSdnVnetsFirewallOptionsRB -Delete "TEST_VALUE" -LogLevelForward "TEST_VALUE" -PolicyForward "TEST_VALUE" -Enable "TEST_VALUE" -Digest "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterSdnVnetsFirewallOptionsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
