#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.3
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterReplicationRB' {
    Context 'PVEPUTClusterReplicationRB' {
        It 'Initialize-PVEPUTClusterReplicationRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterReplicationRB -Comment "TEST_VALUE" -Id "TEST_VALUE" -Rate "TEST_VALUE" -RemoveJob "TEST_VALUE" -Delete "TEST_VALUE" -Source "TEST_VALUE" -Schedule "TEST_VALUE" -Digest "TEST_VALUE" -Disable "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterReplicationRB
            #$NewObject.property | Should -Be 0
        }
    }
}
