#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterMappingPciRB' {
    Context 'PVEPUTClusterMappingPciRB' {
        It 'Initialize-PVEPUTClusterMappingPciRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterMappingPciRB -Delete "TEST_VALUE" -LiveMigrationCapable "TEST_VALUE" -Description "TEST_VALUE" -Map "TEST_VALUE" -Digest "TEST_VALUE" -Mdev "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterMappingPciRB
            #$NewObject.property | Should -Be 0
        }
    }
}
