#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterSdnDnsRB' {
    Context 'PVEPUTClusterSdnDnsRB' {
        It 'Initialize-PVEPUTClusterSdnDnsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterSdnDnsRB -Delete "TEST_VALUE" -Digest "TEST_VALUE" -Url "TEST_VALUE" -Reversemaskv6 "TEST_VALUE" -Dns "TEST_VALUE" -Ttl "TEST_VALUE" -Key "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterSdnDnsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
