#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterOptionsRB' {
    Context 'PVEPUTClusterOptionsRB' {
        It 'Initialize-PVEPUTClusterOptionsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterOptionsRB -Notify "TEST_VALUE" -Bwlimit "TEST_VALUE" -Keyboard "TEST_VALUE" -Crs "TEST_VALUE" -Ha "TEST_VALUE" -Migration "TEST_VALUE" -NextId "TEST_VALUE" -Fencing "TEST_VALUE" -RegisteredTags "TEST_VALUE" -Webauthn "TEST_VALUE" -Delete "TEST_VALUE" -MacPrefix "TEST_VALUE" -UserTagAccess "TEST_VALUE" -ConsentText "TEST_VALUE" -EmailFrom "TEST_VALUE" -U2f "TEST_VALUE" -TagStyle "TEST_VALUE" -HttpProxy "TEST_VALUE" -MigrationUnsecure "TEST_VALUE" -Language "TEST_VALUE" -Console "TEST_VALUE" -Replication "TEST_VALUE" -Description "TEST_VALUE" -MaxWorkers "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterOptionsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
