#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterHaResourcesRB' {
    Context 'PVEPUTClusterHaResourcesRB' {
        It 'Initialize-PVEPUTClusterHaResourcesRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterHaResourcesRB -Digest "TEST_VALUE" -Group "TEST_VALUE" -State "TEST_VALUE" -Delete "TEST_VALUE" -MaxRelocate "TEST_VALUE" -Comment "TEST_VALUE" -MaxRestart "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterHaResourcesRB
            #$NewObject.property | Should -Be 0
        }
    }
}
