#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterMappingDirRB' {
    Context 'PVEPUTClusterMappingDirRB' {
        It 'Initialize-PVEPUTClusterMappingDirRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterMappingDirRB -Description "TEST_VALUE" -Digest "TEST_VALUE" -Delete "TEST_VALUE" -Id "TEST_VALUE" -Map "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterMappingDirRB
            #$NewObject.property | Should -Be 0
        }
    }
}
