#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.2
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterOptionsRB' {
    Context 'PVEPUTClusterOptionsRB' {
        It 'Initialize-PVEPUTClusterOptionsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterOptionsRB -Webauthn "TEST_VALUE" -Keyboard "TEST_VALUE" -NextId "TEST_VALUE" -TagStyle "TEST_VALUE" -Description "TEST_VALUE" -UserTagAccess "TEST_VALUE" -MaxWorkers "TEST_VALUE" -MigrationUnsecure "TEST_VALUE" -Migration "TEST_VALUE" -MacPrefix "TEST_VALUE" -Fencing "TEST_VALUE" -Crs "TEST_VALUE" -Delete "TEST_VALUE" -Ha "TEST_VALUE" -RegisteredTags "TEST_VALUE" -U2f "TEST_VALUE" -Notify "TEST_VALUE" -EmailFrom "TEST_VALUE" -Language "TEST_VALUE" -Console "TEST_VALUE" -Bwlimit "TEST_VALUE" -HttpProxy "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterOptionsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
