#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 8.4.0
# Version: 8.4.0
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTClusterNotificationsMatchersRB' {
    Context 'PVEPUTClusterNotificationsMatchersRB' {
        It 'Initialize-PVEPUTClusterNotificationsMatchersRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTClusterNotificationsMatchersRB -Mode "TEST_VALUE" -Delete "TEST_VALUE" -Target "TEST_VALUE" -MatchField "TEST_VALUE" -Disable "TEST_VALUE" -MatchSeverity "TEST_VALUE" -Digest "TEST_VALUE" -MatchCalendar "TEST_VALUE" -Comment "TEST_VALUE" -InvertMatch "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTClusterNotificationsMatchersRB
            #$NewObject.property | Should -Be 0
        }
    }
}
