#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesLxcResizeRB' {
    Context 'PVEPUTNodesLxcResizeRB' {
        It 'Initialize-PVEPUTNodesLxcResizeRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesLxcResizeRB -Vmid "TEST_VALUE" -Digest "TEST_VALUE" -Disk "TEST_VALUE" -Size "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesLxcResizeRB
            #$NewObject.property | Should -Be 0
        }
    }
}
