#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.6
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesLxcFirewallOptionsRB' {
    Context 'PVEPUTNodesLxcFirewallOptionsRB' {
        It 'Initialize-PVEPUTNodesLxcFirewallOptionsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesLxcFirewallOptionsRB -PolicyIn "TEST_VALUE" -Digest "TEST_VALUE" -PolicyOut "TEST_VALUE" -Dhcp "TEST_VALUE" -Ipfilter "TEST_VALUE" -Delete "TEST_VALUE" -Enable "TEST_VALUE" -LogLevelOut "TEST_VALUE" -Macfilter "TEST_VALUE" -Ndp "TEST_VALUE" -LogLevelIn "TEST_VALUE" -Radv "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesLxcFirewallOptionsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
