#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesConfigRB' {
    Context 'PVEPUTNodesConfigRB' {
        It 'Initialize-PVEPUTNodesConfigRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesConfigRB -AcmedomainN "TEST_VALUE" -Delete "TEST_VALUE" -Description "TEST_VALUE" -Wakeonlan "TEST_VALUE" -Acme "TEST_VALUE" -StartallOnbootDelay "TEST_VALUE" -Digest "TEST_VALUE" -BallooningTarget "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesConfigRB
            #$NewObject.property | Should -Be 0
        }
    }
}
