#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesConfigRB' {
    Context 'PVEPUTNodesConfigRB' {
        It 'Initialize-PVEPUTNodesConfigRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesConfigRB -AcmedomainN "TEST_VALUE" -Wakeonlan "TEST_VALUE" -Delete "TEST_VALUE" -StartallOnbootDelay "TEST_VALUE" -BallooningTarget "TEST_VALUE" -Digest "TEST_VALUE" -Description "TEST_VALUE" -Acme "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesConfigRB
            #$NewObject.property | Should -Be 0
        }
    }
}
