#
# Proxmox VE
# Generated module to access all Proxmox VE Api Endpoints
# Version: 0.5
# Contact: amna.wolf@gmail.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesQemuConfigRB' {
    Context 'PVEPUTNodesQemuConfigRB' {
        It 'Initialize-PVEPUTNodesQemuConfigRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesQemuConfigRB -SpiceEnhancements "TEST_VALUE" -Lock "TEST_VALUE" -Onboot "TEST_VALUE" -Cdrom "TEST_VALUE" -Template "TEST_VALUE" -Ciupgrade "TEST_VALUE" -Hookscript "TEST_VALUE" -Digest "TEST_VALUE" -Cpu "TEST_VALUE" -Rng0 "TEST_VALUE" -Agent "TEST_VALUE" -Cpulimit "TEST_VALUE" -Scsihw "TEST_VALUE" -Boot "TEST_VALUE" -Vmgenid "TEST_VALUE" -ParallelN "TEST_VALUE" -NetN "TEST_VALUE" -Smbios1 "TEST_VALUE" -SerialN "TEST_VALUE" -Tpmstate0 "TEST_VALUE" -Name "TEST_VALUE" -Bios "TEST_VALUE" -Vga "TEST_VALUE" -Sshkeys "TEST_VALUE" -Nameserver "TEST_VALUE" -Memory "TEST_VALUE" -IdeN "TEST_VALUE" -Kvm "TEST_VALUE" -Efidisk0 "TEST_VALUE" -Startdate "TEST_VALUE" -Arch "TEST_VALUE" -Cpuunits "TEST_VALUE" -Autostart "TEST_VALUE" -Localtime "TEST_VALUE" -Keyboard "TEST_VALUE" -Keephugepages "TEST_VALUE" -MigrateSpeed "TEST_VALUE" -Hotplug "TEST_VALUE" -Cipassword "TEST_VALUE" -Bootdisk "TEST_VALUE" -Description "TEST_VALUE" -Vmstatestorage "TEST_VALUE" -Cicustom "TEST_VALUE" -Machine "TEST_VALUE" -Affinity "TEST_VALUE" -Sockets "TEST_VALUE" -Smp "TEST_VALUE" -Tablet "TEST_VALUE" -IpconfigN "TEST_VALUE" -Numa "TEST_VALUE" -Delete "TEST_VALUE" -Startup "TEST_VALUE" -AmdSev "TEST_VALUE" -HostpciN "TEST_VALUE" -Cores "TEST_VALUE" -Ostype "TEST_VALUE" -Tags "TEST_VALUE" -Shares "TEST_VALUE" -Vcpus "TEST_VALUE" -VirtioN "TEST_VALUE" -Skiplock "TEST_VALUE" -Freeze "TEST_VALUE" -ScsiN "TEST_VALUE" -Force "TEST_VALUE" -SataN "TEST_VALUE" -Ivshmem "TEST_VALUE" -Watchdog "TEST_VALUE" -UnusedN "TEST_VALUE" -Protection "TEST_VALUE" -MigrateDowntime "TEST_VALUE" -Balloon "TEST_VALUE" -Hugepages "TEST_VALUE" -VarArgs "TEST_VALUE" -Revert "TEST_VALUE" -Acpi "TEST_VALUE" -NumaN "TEST_VALUE" -Searchdomain "TEST_VALUE" -Tdf "TEST_VALUE" -Ciuser "TEST_VALUE" -VirtiofsN "TEST_VALUE" -UsbN "TEST_VALUE" -Reboot "TEST_VALUE" -Audio0 "TEST_VALUE" -Citype "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesQemuConfigRB
            #$NewObject.property | Should -Be 0
        }
    }
}
