#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesQemuSnapshotConfigRB' {
    Context 'PVEPUTNodesQemuSnapshotConfigRB' {
        It 'Initialize-PVEPUTNodesQemuSnapshotConfigRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesQemuSnapshotConfigRB -Snapname "TEST_VALUE" -Description "TEST_VALUE" -Vmid "TEST_VALUE" -Node "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesQemuSnapshotConfigRB
            #$NewObject.property | Should -Be 0
        }
    }
}
