#
# Proxmox PowerShell VE
# Generated module to access all Proxmox VE Api Endpoints. This module has been generated from the proxmox api description v. 9.1.1
# Version: 9.1.1
# Contact: mail@timo-wolf.de
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesQemuFirewallOptionsRB' {
    Context 'PVEPUTNodesQemuFirewallOptionsRB' {
        It 'Initialize-PVEPUTNodesQemuFirewallOptionsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesQemuFirewallOptionsRB -Dhcp "TEST_VALUE" -PolicyOut "TEST_VALUE" -Delete "TEST_VALUE" -Enable "TEST_VALUE" -Ipfilter "TEST_VALUE" -Macfilter "TEST_VALUE" -LogLevelIn "TEST_VALUE" -Ndp "TEST_VALUE" -Digest "TEST_VALUE" -LogLevelOut "TEST_VALUE" -PolicyIn "TEST_VALUE" -Radv "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesQemuFirewallOptionsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
