#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTNodesDnsRB' {
    Context 'PVEPUTNodesDnsRB' {
        It 'Initialize-PVEPUTNodesDnsRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTNodesDnsRB -Search "TEST_VALUE" -Dns3 "TEST_VALUE" -Node "TEST_VALUE" -Dns1 "TEST_VALUE" -Dns2 "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTNodesDnsRB
            #$NewObject.property | Should -Be 0
        }
    }
}
