#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVEPUTStorageRB' {
    Context 'PVEPUTStorageRB' {
        It 'Initialize-PVEPUTStorageRB' {
            # a simple test to create an object
            #$NewObject = Initialize-PVEPUTStorageRB -Password "TEST_VALUE" -PruneBackups "TEST_VALUE" -Blocksize "TEST_VALUE" -Transport "TEST_VALUE" -Saferemove "TEST_VALUE" -SkipCertVerification "TEST_VALUE" -LioTpg "TEST_VALUE" -CreateBasePath "TEST_VALUE" -Nodes "TEST_VALUE" -Krbd "TEST_VALUE" -Fuse "TEST_VALUE" -Subdir "TEST_VALUE" -Content "TEST_VALUE" -FsName "TEST_VALUE" -TaggedOnly "TEST_VALUE" -DataPool "TEST_VALUE" -Fingerprint "TEST_VALUE" -Pool "TEST_VALUE" -SaferemoveThroughput "TEST_VALUE" -Preallocation "TEST_VALUE" -Delete "TEST_VALUE" -EncryptionKey "TEST_VALUE" -Port "TEST_VALUE" -Monhost "TEST_VALUE" -Namespace "TEST_VALUE" -Smbversion "TEST_VALUE" -MaxProtectedBackups "TEST_VALUE" -IsMountpoint "TEST_VALUE" -Disable "TEST_VALUE" -Username "TEST_VALUE" -MasterPubkey "TEST_VALUE" -Nocow "TEST_VALUE" -Nowritecache "TEST_VALUE" -Mkdir "TEST_VALUE" -ComstarHg "TEST_VALUE" -Server2 "TEST_VALUE" -Maxfiles "TEST_VALUE" -Server "TEST_VALUE" -Digest "TEST_VALUE" -Mountpoint "TEST_VALUE" -Domain "TEST_VALUE" -Keyring "TEST_VALUE" -ComstarTg "TEST_VALUE" -Bwlimit "TEST_VALUE" -Options "TEST_VALUE" -Format "TEST_VALUE" -CreateSubdirs "TEST_VALUE" -Storage "TEST_VALUE" -Shared "TEST_VALUE" -Sparse "TEST_VALUE" -ContentDirs "TEST_VALUE"
            #$NewObject | Should -BeOfType PUTStorageRB
            #$NewObject.property | Should -Be 0
        }
    }
}
